apiVersion: v1
kind: Service
metadata:
  name: activiti-service
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.activiti.serviceAnnotations }}
    {{ toYaml .Values.activiti.serviceAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: activiti
  ports:
      - name: 'activiti'
        protocol: TCP
        port: 30000
        targetPort: 8080
  {{- if .Values.general.serviceType }}
  type: {{ .Values.general.serviceType }}
  {{- end }}