apiVersion: v1
kind: ConfigMap
metadata:
  name: activiti-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: activiti
data:
#     # -- Cross Origin Resource Sharing configuration toggle
#   ACTIVITI_CORS_ENABLED: true
#   # -- Cross Origin Resource Sharing configuration allowed origins
#   # (list of strings)
#   # ACTIVITI_CORS_ALLOWED_ORIGINS: "*"
#   # -- Cross Origin Resource Sharing configuration allowed origins
#   # (list of glob-like patterns)
#   ACTIVITI_CORS_ALLOWED_ORIGIN_PATTERNS: "*"
#   # -- Cross Origin Resource Sharing configuration allowed http methods
#   ACTIVITI_CORS_ALLOWED_METHODS: "GET,POST,HEAD,OPTIONS,PUT,DELETE"
#   # -- Cross Origin Resource Sharing configuration allowed http headers
#   ACTIVITI_CORS_ALLOWED_HEADERS: >-
#     Authorization,Content-Type,Cache-Control,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,X-CSRF-Token
#   # -- Cross Site Resource Forgery configuration toggle
#   ACTIVITI_CSRF_DISABLED: "true"
#   -- ElasticSearch configuration
#   ACTIVITI_ES_SERVER_TYPE: "rest"
#   ACTIVITI_ES_REST_CLIENT_ADDRESS: "localhost"
#   ACTIVITI_ES_REST_CLIENT_PORT: "9200"
#   ACTIVITI_ES_REST_CLIENT_SCHEMA: "http"
#   ACTIVITI_ES_REST_CLIENT_AUTH_ENABLED: "false"
#   ACTIVITI_ES_REST_CLIENT_USERNAME: "admin"
#   ACTIVITI_ES_REST_CLIENT_PASSWORD: "esadmin"
#   ACTIVITI_ES_REST_CLIENT_KEYSTORE: ""
#   ACTIVITI_ES_REST_CLIENT_KEYSTORE_TYPE: "jks"
#   ACTIVITI_ES_REST_CLIENT_KEYSTORE_PASSWORD: ""
#   ACTIVITI_ADMIN_EMAIL:
#   ACTIVITI_ADMIN_PASSWORD_HASH:
#   ACTIVITI_LICENSE_MULTI_TENANT:
#   -- Alfresco Identity Service configuration toggle
#   IDENTITY_SERVICE_ENABLED: "false"
#   # -- Alfresco Identity Service Realm
#   IDENTITY_SERVICE_REALM: "alfresco"
#   # -- Alfresco Identity Service address
#   IDENTITY_SERVICE_AUTH: "http://localhost:8080/auth"
#   # -- Alfresco Identity Service force using SSL
#   IDENTITY_SERVICE_SSL_REQUIRED: "none"
#   # -- Alfresco Identity Service resource name to use
#   IDENTITY_SERVICE_RESOURCE: "alfresco"
#   # -- Alfresco Identity Service Attribute to map to user login
#   IDENTITY_SERVICE_PRINCIPAL_ATTRIBUTE: "email"
#   # -- Alfresco Identity Service refresh service token
#   IDENTITY_SERVICE_ALWAYS_REFRESH_TOKEN: "true"
#   # -- Alfresco Identity Service Bearer only toggle
#   IDENTITY_SERVICE_AUTODETECT_BEARER_ONLY: "true"
#   # -- Alfresco Identity Service token storage configuration
#   IDENTITY_SERVICE_TOKEN_STORE: "session"
#   # -- Alfresco Identity Service allow basic authentication
#   # (should only be used over SSL)
#   IDENTITY_SERVICE_ENABLE_BASIC_AUTH: "true"
#   # -- Alfresco Identity Service public client toggle
#   IDENTITY_SERVICE_PUBLIC_CLIENT: "true"
#   # -- Alfresco Identity Service browser initiated logout toggle
#   IDENTITY_SERVICE_USE_BROWSER_BASED_LOGOUT: "true"
#   # -- Alfresco Identity Service application secret
#   IDENTITY_CREDENTIALS_SECRET: ""
  {{- if .Values.activiti.additionalEnvironmentVariables }}
  {{ toYaml .Values.activiti.additionalEnvironmentVariables | nindent 2 }}
  {{- end }}