{{- if .Values.postgresqlActiviti.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: postgresql-activiti-service
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.postgresqlActiviti.serviceAnnotations }}
    {{ toYaml .Values.postgresqlActiviti.serviceAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: postgresql-activiti
  ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432
{{- end }}