general:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  dbActiviti: {}
  dbActivitiAdmin: {}
  secrets:
    dbActiviti:
      selfManaged: false
    dbActivitiAdmin:
      selfManaged: false


postgresqlActiviti:
  enabled: true
  image:
    registry: 'docker.io'
    repository: 'xenit/postgres'
    tag: 'latest'
  strategy:
    type: Recreate
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
postgresqlActivitiAdmin:
  enabled: true
  image:
    registry: 'docker.io'
    repository: 'xenit/postgres'
    tag: 'latest'
  strategy:
    type: Recreate
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"

ingress:
  protocol: 'http'
  ingressAnnotations:
    kubernetes.io/ingress.class: "nginx"
  defaultBackend:
    mapToRootOnly: true
    service: nginx-default-service
    port: 30403
  blockedPaths:
    enabled: false

activiti:
  license:
    enabled: false
    path: /home/alfresco/.activiti/enterprise-license/activiti.lic
  image:
    registry: 'docker.io'
    repository: 'alfresco/process-services'
    tag: '24.2.0'
  strategy:
    type: RollingUpdate
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 8Gi
  livenessProbe:
    failureThreshold: 5
    httpGet:
      path: /activiti-app/app/rest/locale
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 25
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    failureThreshold: 5
    httpGet:
      path: /activiti-app/app/rest/locale
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 25
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  ingress:
    enabled: true
  additionalEnvironmentVariables:
    ACTIVITI_DATASOURCE_DRIVER: "org.postgresql.Driver"
    ACTIVITI_DATASOURCE_URL: "jdbc:postgresql://postgresql-activiti-service:5432/activiti?characterEncoding=UTF-8"
    ACTIVITI_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
activitiAdmin:
  image:
    registry: 'docker.io'
    repository: 'alfresco/process-services-admin'
    tag: '24.2.0'
  strategy:
    type: RollingUpdate
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 2Gi
  livenessProbe:
    failureThreshold: 5
    httpGet:
      path: /activiti-admin/
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 25
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    failureThreshold: 5
    httpGet:
      path: /activiti-admin/
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 25
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  ingress:
    enabled: true
  additionalEnvironmentVariables:
    ACTIVITI_ADMIN_DATASOURCE_DRIVER: "org.postgresql.Driver"
    ACTIVITI_ADMIN_DATASOURCE_URL: "jdbc:postgresql://postgresql-activiti-admin-service:5432/activiti-admin?characterEncoding=UTF-8"
    ACTIVITI_ADMIN_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
    ACTIVITI_ADMIN_REST_APP_HOST: 'http://activiti-service'
    ACTIVITI_ADMIN_REST_APP_PORT: '30000'
persistentStorage:
  postgresqlActiviti:
    enabled: true
    storageClassName: ""
    storage: 2
    efs:
      volumeHandle: ""
  postgresqlActivitiAdmin:
    enabled: true
    storageClassName: ""
    storage: 2
    efs:
      volumeHandle: ""