{{- if or (eq .Values.persistentStorage.postgresqlActiviti.storageClassName "efs-storage-class") (eq .Values.persistentStorage.postgresqlActivitiAdmin.storageClassName "efs-storage-class") -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-storage-class
provisioner: efs.csi.aws.com
{{- end }}