# Defines the deployment for the alfresco content repository app
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aps-ingress
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.ingress.ingressAnnotations}}
    {{ toYaml .Values.ingress.ingressAnnotations | nindent 4 }}
    {{- end }}
spec:
  {{- if eq .Values.ingress.protocol "https" }}
  tls:
    - hosts:
        # Provide the desired host
        - {{ required "A host where your activiti services can be reached on must be specified in values.ingress.host" .Values.ingress.host }}
      # Provide a unique secret to store the SSL credentials
      secretName: tls-activiti-{{ .Release.Name }}-secret
  {{- end }}
  {{- if .Values.ingress.defaultBackend }}
  defaultBackend:
    service:
      name: {{ .Values.ingress.defaultBackend.service }}
      port:
        number: {{ .Values.ingress.defaultBackend.port }}
  {{- end }}
  rules:
  - host: {{ required "A host where your activiti services can be reached on must be specified in values.ingress.host" .Values.ingress.host }}
    http:
      paths:
      {{- if .Values.ingress.defaultPath }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ingress.defaultPath.service }}
            port:
              number: {{ .Values.ingress.defaultPath.port }}
      {{- end }}
      {{- if .Values.activiti.ingress.enabled }}
      - path: /activiti-app
        pathType: Prefix
        backend:
          service:
            name: activiti-service
            port:
              number: 30000
      {{- end }}
      {{- if and .Values.activitiAdmin.enabled .Values.activitiAdmin.ingress.enabled }}
      - path: /activiti-admin
        pathType: Prefix
        backend:
          service:
            name: activiti-admin-service
            port:
              number: 30100
      {{- end }}
      {{- if .Values.ingress.blockedPaths.enabled }}
      {{- range .Values.ingress.blockedPaths.paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: nginx-default-service
            port:
              number: 30403
      {{- end }}
      {{- end }}
      {{- if .Values.ingress.additionalPaths }}
      {{ toYaml .Values.ingress.additionalPaths | nindent 6 }}
      {{- end }}
