apiVersion: v1
kind: ConfigMap
metadata:
  name: alfresco-activity-admin-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: alfresco-activity-admin
data:
  DB_DRIVER: {{ quote .Values.acs.dbDriver }} //TODO
  {{- if .Values.activityAdmin.additionalEnvironmentVariables }}
  {{ toYaml .Values.activityAdmin.additionalEnvironmentVariables | nindent 2 }}
  {{- end }}