name: 'Continuous Integration'
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  integration-testing:
    runs-on: ubuntu-latest-4-cores
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4
      - name: Install kind
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          install_only: true
      - uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Check
        working-directory: integration-testing
        run: ./gradlew check -i
      - name: Upload Artifact
        if: success() || failure()
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4
        with:
          name: test-result
          path: /home/runner/work/**/build/reports
          retention-days: 2
  publish:
    needs: [ integration-testing ]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Parse version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4
      - name: Package Helm Chart
        run: helm package xenit-aps --version "${{ env.version }}"
      - name: publish to cloudsmith
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_APIKEY }}
          command: 'push'
          format: 'helm'
          owner: 'xenit'
          repo: 'open-source'
          file: 'activiti-${{ env.version }}.tgz'